/**
 * 서버 에러 코드 상수 — derby_system_spec_v1.md §6과 문자열 1:1.
 * 클라이언트는 이 문자열로 분기한다 (서버 계약 — 임의 변경 금지).
 */
export const ErrorCodes = {
  // 클라이언트 전용 (서버 미도달)
  NETWORK: 'NETWORK',

  COMMON_INVALID_REQUEST: 'COMMON_INVALID_REQUEST',
  COMMON_NOT_FOUND: 'COMMON_NOT_FOUND',
  COMMON_INTERNAL_ERROR: 'COMMON_INTERNAL_ERROR',

  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_INVALID_DEVICE_ID: 'AUTH_INVALID_DEVICE_ID',
  AUTH_INVALID_TIMEZONE: 'AUTH_INVALID_TIMEZONE',

  SETTINGS_INVALID_TIMEZONE: 'SETTINGS_INVALID_TIMEZONE',
  SETTINGS_NICKNAME_TOO_LONG: 'SETTINGS_NICKNAME_TOO_LONG',
  SETTINGS_TIMEZONE_CHANGE_TOO_OFTEN: 'SETTINGS_TIMEZONE_CHANGE_TOO_OFTEN',

  TASK_ASSIGNMENT_NOT_FOUND: 'TASK_ASSIGNMENT_NOT_FOUND',
  TASK_INVALID_REACTION: 'TASK_INVALID_REACTION',
  TASK_RETRY_EXHAUSTED: 'TASK_RETRY_EXHAUSTED',

  CHAT_LIMIT_EXCEEDED: 'CHAT_LIMIT_EXCEEDED',
  CHAT_CONTENT_TOO_LONG: 'CHAT_CONTENT_TOO_LONG',
  CHAT_CONCURRENT_REQUEST: 'CHAT_CONCURRENT_REQUEST',
  CHAT_MESSAGE_NOT_FOUND: 'CHAT_MESSAGE_NOT_FOUND',

  LLM_UPSTREAM_ERROR: 'LLM_UPSTREAM_ERROR',
  LLM_TIMEOUT: 'LLM_TIMEOUT',
  LLM_BUDGET_EXHAUSTED: 'LLM_BUDGET_EXHAUSTED',

  DIARY_CANDIDATE_NOT_FOUND: 'DIARY_CANDIDATE_NOT_FOUND',
  DIARY_ENTRY_NOT_FOUND: 'DIARY_ENTRY_NOT_FOUND',
  DIARY_SLOT_FULL: 'DIARY_SLOT_FULL',
  DIARY_REWRITE_LIMIT: 'DIARY_REWRITE_LIMIT',
  DIARY_PREMIUM_ONLY: 'DIARY_PREMIUM_ONLY',

  PUSH_INVALID_TOKEN: 'PUSH_INVALID_TOKEN',
  PUSH_INVALID_DAILY_COUNT: 'PUSH_INVALID_DAILY_COUNT',
  PUSH_LOG_NOT_FOUND: 'PUSH_LOG_NOT_FOUND',

  BILLING_WEBHOOK_UNAUTHORIZED: 'BILLING_WEBHOOK_UNAUTHORIZED',
  BILLING_SYNC_FAILED: 'BILLING_SYNC_FAILED',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

/** 장난 금지 구역 — derbyMessage 대신 정자세 message 우선 표시 */
export function isSeriousZone(code: string): boolean {
  return code.startsWith('AUTH_') || code.startsWith('BILLING_');
}
